# Generated by Django 5.2.9 on 2025-12-08 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('player_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('winner', 'Winner'), ('second', 'Second')], default=None, max_length=6)),
                ('kills', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('match_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('player_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playerprofile')),
            ],
        ),
    ]
