# Generated by Django 5.2.9 on 2025-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='join_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='player_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
